const DATA = {

  languages: [
    { id:"de",   flag:"🇩🇪", name:"German",  sub:"German lyrics" },
    { id:"en",   flag:"🇬🇧", name:"English", sub:"English lyrics" },
  ],

 persons: [
  { id:"partner",     icon:"💑", label:"Partner",          sub:"Husband, wife, boyfriend, girlfriend, fiancé" },
  { id:"parents",     icon:"👨‍👩‍👧", label:"Parents",          sub:"Mum, dad, both together, or individually" },
  { id:"child",       icon:"🌱", label:"Child",             sub:"Newborn, toddler, daughter, or son" },
  { id:"friend",      icon:"🤝", label:"Best Friend(s)",       sub:"Best friend, the girls, the boys, squad" },
  { id:"grandparent", icon:"👴", label:"Grandparents",         sub:"Grandma, grandpa — together or individually" },
  { id:"sibling",     icon:"🫂", label:"Sibling",           sub:"Brother, sister, or twin" },
  { id:"pet",         icon:"🐾", label:"Pet",               sub:"Dog, cat, horse, or any beloved animal" },
  { id:"colleague",   icon:"💼", label:"Colleague / Boss",   sub:"Work friend, mentor, or the whole team" },
  { id:"ex",          icon:"💔", label:"Ex",                sub:"Closure, nostalgia, or one last thing to say" },
  { id:"self",        icon:"🪞", label:"Myself",               sub:"A personal anthem, self-love, or a milestone" },
  { id:"other",       icon:"🎁", label:"Someone Else",         sub:"Anyone else who deserves a song" },
],

occasions: [
  { id:"birthday",        icon:"🎂", label:"Birthday",                    sub:"Milestone or everyday — every birthday counts",          for:["partner","parents","child","friend","grandparent","sibling","pet","colleague","self","other"] },
  { id:"anniversary",     icon:"❤️", label:"Anniversary",                 sub:"Celebrating love and time together",                     for:["partner","parents","grandparent", "other"] },
  { id:"wedding",         icon:"💍", label:"Wedding",                     sub:"First dance, vows, speech, or gift",                     for:["partner","friend","sibling","other"] },
  { id:"engagement",      icon:"💎", label:"Engagement",                  sub:"The moment it all changed",                              for:["partner","friend","sibling","other"] },
  { id:"newbaby",         icon:"🍼", label:"New Baby / Christening",      sub:"Celebrating a new arrival into the world",               for:["partner","friend","sibling","other"] },
  { id:"graduation",      icon:"🎓", label:"Graduation",                  sub:"Years of hard work — finally paid off",                  for:["child","sibling","friend","self","other"] },
  { id:"retirement",      icon:"🌅", label:"Retirement / Farewell",       sub:"A new chapter — no more Mondays",                        for:["parents","grandparent","colleague","other","friend"] },
  { id:"thankyou",        icon:"🙏", label:"Thank You",                   sub:"Mother's Day, Father's Day, or heartfelt gratitude",     for:["parents","grandparent","friend","colleague","other"] },
  { id:"mothersday",      icon:"🌸", label:"Mother's Day",                sub:"A dedicated tribute to the woman who raised you",        for:["parents","other"] },
  { id:"fathersday",      icon:"🪵", label:"Father's Day",                sub:"A proper thank-you for the man who showed up",           for:["parents","other"] },
  { id:"newchapter",      icon:"🚪", label:"New Chapter",                 sub:"Moving, new job, emigrating, or a big life change",      for:["friend","sibling","colleague","self","other"] },
  { id:"recovery",        icon:"💪", label:"Recovery / Overcoming",       sub:"Beating illness, addiction, or something tough",         for:["parents","child","friend","sibling","self","other"] },
  { id:"longdistance",    icon:"✈️", label:"Long Distance / Missing You", sub:"Miles apart but always close",                           for:["partner","friend","sibling","child","other"] },
  { id:"roast",           icon:"🔥", label:"Roast / Joke Song",           sub:"Funny, affectionate, and absolutely surgical",           for:["friend","sibling","partner","colleague","other"] },
  { id:"apology",         icon:"🙈", label:"Apology Song",                sub:"You messed up. A song fixes everything. Probably.",      for:["partner","friend","sibling","parents","other"] },
  { id:"proposal",        icon:"💍", label:"Marriage Proposal",           sub:"The song playing when you pop the question",             for:["partner"] },
  { id:"leavingwork",     icon:"🏃", label:"Leaving Work Party",          sub:"For the colleague who finally escaped",                  for:["colleague","friend","other"] },
  { id:"divorce",         icon:"✌️", label:"Divorce / Moving On",         sub:"A new era. No bitterness — just freedom. Okay, maybe a little.", for:["self","friend","other"] },
  { id:"other",           icon:"🎊", label:"Other occasion",              sub:"Something unique — you'll tell us below",                for:["partner","parents","child","friend","grandparent","sibling","pet","colleague","self","ex","other"] },
],

moods: {
  "partner|anniversary":     ["Feel like a love letter 💌","Make us both cry happy tears 😭","Capture exactly who we are 🥂","Be light, fun, and romantic 💃"],
  "partner|wedding":         ["Feel like our first dance 💃","Make everyone in the room feel it ❤️","Be intimate — just for us 🤫","Be joyful and celebratory 🎉"],
  "partner|engagement":      ["Capture the exact moment we said yes 💎","Be over-the-moon joyful 🎉","Feel tender and full of disbelief 🥲","Be the song we play forever 💌"],
  "partner|birthday":        ["Feel romantic and personal 💌","Be tender and heartfelt 💛","Be fun and celebratory 🎉","Capture our whole love story 🥂"],
  "partner|justbecause":     ["Feel like a warm hug 🤗","Say what I can't say out loud 🌹","Be playful and fun between us 😄","Be deep and meaningful 💛"],
  "partner|longdistance":    ["Ache with how much I miss them 💔","Be hopeful — we'll close the distance 🌍","Feel like I'm right there beside them 🤗","Be bittersweet and real 🥲"],
  "partner|proposal":        ["Build slowly and explode with joy 💍","Make everyone watching cry 😭","Be romantic but unmistakably us 🥂","Be the best story we ever tell 🌟"],
  "partner|apology":         ["Be genuinely, sincerely sorry 🙈","Be honest — no excuses, just love 💛","Look forward without dwelling 🌱","Be a little grovelling, actually 😅"],
  "parents|birthday":        ["Make them cry (happy tears) 😭","Be warm and grateful 🙏","Be funny and nostalgic 😄","Celebrate everything they've built 🌟"],
  "parents|thankyou":        ["Say thank you from the heart 💛","Feel like a hug they can hear 🤗","Acknowledge their sacrifice 🌹","Make them incredibly proud 🌟"],
  "parents|justbecause":     ["Say all the things I should say more often 💛","Be warm and deeply loving 🤗","Be funny and full of family memories 😄","Remind them they're my whole world 🌟"],
  "parents|mothersday":      ["Say thank you to mum from the heart 🌸","Celebrate everything she's done for the family 🌟","Be warm and full of specific memories 🤗","Make her feel completely loved 💛"],
  "parents|fathersday":      ["Say thank you to dad from the heart 🪵","Celebrate everything he's done for the family 🌟","Be warm and full of specific memories 🤗","Make him feel completely appreciated 💛"],
  "parents|retirement":      ["Celebrate everything they've built over their careers 🌅","Be warm and deeply proud 🌟","Be funny — they've both earned the roast 😄","Paint a picture of this well-deserved next chapter 🌊"],
  "parents|recovery":        ["Say how incredibly proud and relieved I am 💪","Be full of warmth and deep gratitude 🤗","Celebrate the strength they showed 🌟","Remind them how loved they are 💛"],
  "parents|apology":         ["Be genuinely, sincerely sorry 🙈","Be honest about what happened 💛","Acknowledge what they've given me 🌹","Look forward with love and respect 🌱"],
  "parents|anniversary":     ["Celebrate their love story 💕","Make them both cry happy tears 😭","Be warm and full of family gratitude 🏡","Honour everything they've built together 🌟"],
  "grandparent|birthday":    ["Bring the whole family to tears 😭","Celebrate a life well lived 🌟","Be warm and nostalgic 🤗","Be a gift from all the grandchildren 💛"],
  "grandparent|thankyou":    ["Say thank you for a lifetime of love 💛","Feel warm and full of memories 🤗","Celebrate their wisdom 🌟","Be something the whole family can share 🎁"],
  "grandparent|justbecause": ["Say they are loved beyond words 💛","Be full of memories only we share 🤗","Be funny — they've earned a laugh 😄","Thank them for everything they've quietly given 🌟"],
  "grandparent|memorial":    ["Be a quiet, beautiful farewell 🕊️","Celebrate the full, remarkable life they lived 🌟","Carry their memory through the generations 💛","Say all the things we're glad we said 🌹"],
  "parents|memorial":        ["Be a gentle tribute to everything they gave 🕊️","Celebrate the full life they lived 🌟","Say all the things I'm glad I said 💛","Carry their memory forward for the whole family 🌹"],
  "grandparent|retirement":  ["Celebrate a lifetime of work and dedication 🌅","Be warm and full of family pride 🌟","Be funny — they can take it 😄","Wish them joy in this new chapter 🌊"],
  "grandparent|anniversary": ["Celebrate decades of love and commitment 💕","Make the whole family emotional 😭","Be warm and deeply respectful 🌟","Honour a love that built a family 🏡"],
  "child|birthday":          ["Be joyful and uplifting 🎈","Feel like a proud parent moment 🥲","Be fun and just for them 🎊","Capture who they are right now 💛"],
  "child|newbaby":           ["Be gentle and dreamy 🌙","Be a promise from us to them 🌹","Celebrate this new arrival 🎉","Be something they'll treasure forever 🎁"],
  "child|graduation":        ["Overflow with parental pride 🌟","Be warm and look back over the journey 🥲","Be funny — we remember the struggle 😄","Launch them into everything ahead 🚀"],
  "child|newchapter":        ["Be full of love and a little letting go 🌱","Be full of hope for what's ahead 🌟","Be honest — it's hard to watch them fly 🥲","Celebrate who they've become 🎉"],
  "child|recovery":          ["Say how proud I am beyond words 💪","Be deeply warm and full of relief 🤗","Be about strength, not just survival 🌟","Remind them how far they've come 🌱"],
  "child|memorial":          ["Be the gentlest, most loving goodbye 🕊️","Carry every memory and every laugh 💛","Say all the things I hold in my heart 🌹","Be a song for them, always 🌙"],
  "friend|birthday":         ["Roast them (lovingly) 😂","Be heartfelt and sincere 💛","Be a pure celebration banger 🚀","Capture our friendship perfectly 🤝"],
  "friend|wedding":          ["Make them cry at the altar 😭","Roast the couple (kindly) 😂","Get the whole room dancing 🎉","Say what words alone can't 💛"],
  "friend|justbecause":      ["Feel like a warm shoutout 🤝","Be funny and full of inside jokes 😂","Be genuinely touching 💛","Capture what makes us us 🌟"],
  "friend|longdistance":     ["Say I miss them more than I ever admit 💛","Be funny about the distance — it hurts 😂","Feel like a voice note that actually matters 🤗","Be hopeful — we'll be in the same city again 🌍"],
  "friend|newchapter":       ["Be a proud send-off for what comes next 🚀","Be bittersweet and full of shared history 🥲","Be funny — they're leaving and we're not okay 😂","Celebrate everything we've been through 🤝"],
  "friend|roast":            ["Be surgical. Affectionate, but surgical 🔥","Drag every specific habit they have 😂","Balance the roast with genuine love 💛","Be the song that gets played at their wedding 🎉"],
  "friend|memorial":         ["Be warm and full of laughter, like they were 🌟","Say how much our friendship changed me 💛","Be honest and full of love 🕊️","Hold every memory we made together 🤝"],
  "sibling|birthday":        ["Roast them (they'll love it) 😂","Be genuinely heartfelt 💛","Feel like only a sibling could write it 🫂","Be a hype song for their big day 🚀"],
  "sibling|wedding":         ["Be a proud, emotional speech in song form 😭","Roast them in front of everyone 😂","Say what a sibling can't say with words 💛","Get the whole family up dancing 🎉"],
  "sibling|justbecause":     ["Say I'm grateful you're my sibling 🫂","Be a roast disguised as a love song 😂","Be honest about how annoying and wonderful they are 💛","Be a tribute to our shared weirdness 🌟"],
  "sibling|newchapter":      ["Be proud and a little sad to see them go 🥲","Be funny — sibling energy 😂","Be a beautiful send-off for what's next 🌟","Say everything I've never quite managed to say 🫂"],
  "sibling|recovery":        ["Say how proud and relieved I am 💪","Be full of quiet sibling love 💛","Acknowledge the strength I always knew they had 🌟","Be a reminder I'm always in their corner 🫂"],
  "pet|justbecause":         ["Be from the pet's perspective 🐾","Be silly and absolutely chaotic 😄","Be a genuine love letter to our pet 💛","Tell the story of our life together 🌍"],
  "pet|birthday":            ["Be over-the-top adorable 🎂","Be from the pet's point of view 🐾","Be funny about what pets actually care about 😄","Celebrate their whole little life 💛"],
  "pet|memorial":            ["Be a gentle, loving goodbye 🕊️","Celebrate every chaotic, wonderful thing about them 🐾","Say how much smaller life is without them 💛","Hold every cuddle and every memory 🌹"],
  "colleague|leavingwork":   ["Be a chaotic office send-off 🏃","Roast every habit their desk-neighbour endured 😂","Be warm and genuinely celebratory 🌟","Be the highlight of a party they'll never forget 🎉"],
  "colleague|retirement":    ["Celebrate what they built over a career 🌟","Be warm and heartfelt from the whole team 🤝","Be funny — they've earned the roast 😄","Wish them well on this very well-deserved chapter 🌅"],
  "colleague|birthday":      ["Be funny and deeply office-specific 😂","Be warm and team-spirited 🤝","Be a genuine tribute to them as a person 💛","Be the song everyone at work will be humming 🎉"],
  "colleague|roast":         ["Hold nothing back — this is the leaving roast 🔥","Be specific about every quirk. Every. Single. One. 😂","Balance the chaos with genuine warmth 💛","Be legendary. They deserve nothing less. 🌟"],
  "colleague|thankyou":      ["Say thank you for mentorship and guidance 🌟","Be warm and specifically about what they gave 💛","Acknowledge the impact they had on my career 🌱","Be the kind of tribute that makes them tear up a little 🥲"],
  "self|birthday":           ["Be a full self-celebration anthem 🥂","Be reflective — another year, a better me 🪞","Be a little arrogant, actually — I deserve it 😄","Be honest about the journey and proud of it 🌟"],
  "self|newchapter":         ["Be a hype anthem for what's next 🚀","Be reflective and full of intention 🪞","Be honest about the fear and the excitement 🌱","Be the song I play on the first day of everything new 🌅"],
  "self|graduation":         ["Be a victory lap, full volume 🎓","Be reflective — the hard years were worth it 🥲","Launch me into whatever's next 🚀","Be something my future self will thank me for 🌟"],
  "self|recovery":           ["Be about how far I've actually come 💪","Be honest — it was hard, and I made it 🌱","Be an anthem I can return to when it gets hard again 🌟","Be about the version of me that survived 🦋"],
  "self|divorce":            ["Be about freedom and a brand new start ✌️","Be empowering — I choose myself now 💃","Be bittersweet but ultimately hopeful 🌅","Be the song I blast on the drive home alone 😤"],
  "ex|justbecause":          ["Be about closure — the door is finally closed 🚪","Be bittersweet and honest, no anger 🥲","Be about the love that was real, even if it ended 💛","Be the last thing I ever needed to say 💌"],
  "*|memorial":              ["Be a quiet, loving goodbye 🕊️","Celebrate everything they were 🌟","Carry their memory forward 💌","Feel like they're still speaking to us 💛"],
  "*|recovery":              ["Say how incredibly proud I am 💪","Be full of warmth and genuine relief 🤗","Celebrate the strength it took to get here 🌟","Be a reminder they are not alone 💛"],
  "*|roast":                 ["Be affectionate but hold absolutely nothing back 🔥","Be specific — generalities aren't funny 😂","Balance the chaos with a moment of real love 💛","Be the song people quote for years 🌟"],
  "*|apology":               ["Be genuinely, sincerely sorry — no spin 🙈","Be honest about what happened 💛","Be humble and full of love 🌹","Say I know it wasn't okay, and I mean it 🌱"],
  "*|newchapter":            ["Be full of excitement for what's ahead 🚀","Be a little bittersweet about what's left behind 🥲","Be an anthem for the leap of faith 🌟","Be the best send-off they've ever heard 🎉"],
  "default":                 ["Feel warm and heartfelt 💛","Make them feel truly seen 🥲","Be uplifting and celebratory 🎉","Be something they'll never forget 🌟"],
},

  CUSTOM_GENRES = [
  {
    id: "trap",
    name: "Trap",
    desc: "High energy with a gritty, modern bounce.",
    img: "img/characters/trap.jpg",
    bg: "linear-gradient(160deg,#2e112d,#170916)",
    audio: { en: "audio/trap-en.mp3",
           de: "audio/trap-de.mp3"},
    langs: ["en", "de"],
  },
  {
    id: "soulful-pop",
    name: "Soulful Pop",
    desc: "Lyric-driven and close to the bone.",
    img: "img/characters/soulful-pop.jpg",
    bg: "linear-gradient(160deg,#3d2a1f,#281c14)",
    audio: { en: "audio/soulful-pop-en.mp3" },
    langs: ["en"],
  },
  {
    id: "rock-n-roll",
    name: "Rock n Roll",
    desc: "Raw, electrifying, and timeless.",
    img: "img/characters/rock-n-roll.jpg",
    bg: "linear-gradient(160deg,#3d1f1f,#281414)",
    audio: { en: "audio/rock-n-roll-en.mp3" },
    langs: ["en"],
  },
  {
    id: "girly-hip-hop",
    name: "Girly Hip-Hop",
    desc: "Slick rhymes with serious attitude.",
    img: "img/characters/girly-hiphop.png",
    bg: "linear-gradient(160deg,#3d1f36,#281423)",
    audio: { en: "audio/girly-hip-hop-en.mp3" },
    langs: ["en"],
  },
  {
    id: "jazz",
    name: "Jazz",
    desc: "Midnight vibes with a touch of elegance.",
    img: "img/characters/jazz.jpg",
    bg: "linear-gradient(160deg,#1f2a3d,#141c28)",
    audio: { en: "audio/jazz-en.mp3" },
    langs: ["en"],
  },
  {
    id: "blues",
    name: "Blues",
    desc: "Deep, authentic, and full of heart.",
    img: "img/characters/Blueman.png",
    bg: "linear-gradient(160deg,#1f223d,#141628)",
    audio: { en: "audio/blues-en.mp3" },
    langs: ["en"],
  }
],

 
 branches: {
  "partner|anniversary": {
    prompts:["How did you meet? Tell the full story.","What was your very first impression of them?","What quirk of theirs do you secretly love?","What promises are you making for the future?"],
    extendedPrompts:["What moment made you realise you were in love?","What do they do that still makes you smile after all this time?","What is your favourite ordinary moment together?","How has loving them changed you?","What do you want the next chapter to look like?","Something you've never said out loud — what is it?"],
    defaultTempo:"Slow",
  },
  "partner|wedding": {
    prompts:["Describe the moment you knew they were the one.","What do you love most about them right now?","What are your promises to them today?","How do you want your life together to feel?"],
    extendedPrompts:["What's a funny or tender memory only you two would know?","What does your future together look like in your mind?","How has loving them made you a better person?","What do you want them to feel when they hear this song?"],
    defaultTempo:"Slow",
  },
  "partner|engagement": {
    prompts:["How did the proposal happen — every detail.","What was the moment you knew you wanted to marry them?","What do you love about them that you've never put into words?","What does the rest of your life with them look like?"],
    extendedPrompts:["How have they changed you?","What do you want them to feel every time they hear this?","What's a small, ordinary moment that says everything about your relationship?","What are you most excited about for the future?"],
    defaultTempo:"Medium",
  },
  "partner|birthday": {
    prompts:["What do you love about them that no one else sees?","What's your favourite memory together this year?","How do you want them to feel on their birthday?","What are you wishing for them?"],
    extendedPrompts:["How have they changed since you've known them?","What makes them laugh?","What do you want to celebrate about who they are right now?"],
    defaultTempo:"Medium",
  },
  "partner|justbecause": {
    prompts:["What made you want to give them a song today?","What do you love most about them right now?","What's a little moment you share that no one else would know?","What do you want them to feel when they hear this?"],
    extendedPrompts:["How does being with them make your everyday life better?","What's something they do that always makes you smile?","What would you want to say if they were listening right now?"],
    defaultTempo:"Medium",
  },
  "partner|longdistance": {
    prompts:["How long have you been apart and what's the hardest part?","What do you miss most — be specific.","What moment do you replay in your head?","What's waiting for you when you're finally together again?"],
    extendedPrompts:["What does a normal day feel like without them?","What do you do to feel close to them?","What's the first thing you'll do when you're reunited?","What do you want them to remember when it gets hard?"],
    defaultTempo:"Slow",
  },
  "partner|proposal": {
    prompts:["How did you know this was the person you wanted to marry?","What do you love about them that you've never said out loud?","What does the rest of your life with them look like?","What do you want to ask them — in your own words?"],
    extendedPrompts:["What's the moment that changed everything for you?","What's something small about them that says everything?","How have they made you a different person?","What are you promising them with this question?"],
    defaultTempo:"Slow",
  },
  "partner|apology": {
    prompts:["What happened, in your own honest words?","What do you wish you'd done differently?","What do you want them to know about how you feel now?","What are you promising going forward?"],
    extendedPrompts:["What does this relationship mean to you?","What do you want them to understand about your feelings?","What does repair look like for you both?"],
    defaultTempo:"Slow",
  },
  "parents|anniversary": {
    prompts:["How long have they been together and what makes their love special?","What's a memory of them together that captures who they are?","What has their relationship taught you about love?","What do you want to celebrate about their journey together?"],
    extendedPrompts:["What's something they still do that shows their love?","How have they grown together over the years?","What do you hope they know about what they've built?","What are you wishing for their future together?"],
    defaultTempo:"Slow",
  },
  "grandparent|anniversary": {
    prompts:["How many years have they been together?","What's a story about their relationship that the family always tells?","What has their love shown you and your family?","What do you want to celebrate about their life together?"],
    extendedPrompts:["What's something they still do that shows their love after all these years?","What values has their relationship taught the whole family?","What makes their bond special and enduring?","What are you wishing for them?"],
    defaultTempo:"Slow",
  },
  "parents|birthday": {
    prompts:["What have your parents given you that you're most grateful for?","What's a memory that captures who they are together?","What do you want to celebrate about them?","What are your wishes for their next chapter?"],
    extendedPrompts:["What did they sacrifice for you that you understand better now?","How have they shaped who you are?","What do you want them to know about how you feel?","What's something funny that defines your family?"],
    defaultTempo:"Medium",
  },
  "parents|thankyou": {
    prompts:["What's the one thing they did that changed your life?","What did you take for granted that you now appreciate?","How have they shown you love in their own way?","What do you want to say that you've never said?"],
    extendedPrompts:["What values did they teach you?","What memory always makes you emotional?","What are you most proud of in your relationship with them?","What do you hope they know?"],
    defaultTempo:"Slow",
  },
  "parents|memorial": {
    prompts:["What's the memory of them you hold closest?","What did they give you that you carry every day?","What would you want to say if you had one more moment?","How have they shaped who you've become?"],
    extendedPrompts:["What did they teach you without knowing it?","What do you miss most about them being here?","What do you want the world to know about who they were?"],
    defaultTempo:"Slow",
  },
  "parents|mothersday": {
    prompts:["What's the one thing your mum did that changed your life?","What did you take for granted growing up that you're grateful for now?","What's a small, specific thing she does that shows her love?","What do you want to say that you've never quite found the words for?"],
    extendedPrompts:["What values did she teach you without ever stating them?","What memory always makes you emotional when you think about it?","What does she mean to your family?","What do you hope she knows about how she's loved?"],
    defaultTempo:"Slow",
  },
  "parents|fathersday": {
    prompts:["What's the most important thing your dad has given you?","What did he show you about how to be a person?","What's a specific memory with him you'll always hold on to?","What do you want to say that you don't say enough?"],
    extendedPrompts:["What did he do for you that you only understand now you're older?","What's something quiet he did that showed enormous love?","How has he shaped your idea of strength, or family, or home?","What do you hope he knows about how you see him?"],
    defaultTempo:"Medium",
  },
  "parents|retirement": {
    prompts:["What have they built over their careers that deserves celebrating?","What will their lives look like now — what are they looking forward to?","What do you want to say on behalf of the family?","What's a funny or legendary work story about one or both of them?"],
    extendedPrompts:["What has their work ethic taught the people around them?","What will people miss most about them at work?","What does this new chapter mean for the whole family?","What are you wishing for them both?"],
    defaultTempo:"Medium",
  },
  "parents|recovery": {
    prompts:["What did they face and fight through?","What moment made you see how strong they truly are?","What do you want them to know from where you're standing?","What does the road ahead look like together?"],
    extendedPrompts:["What did this experience reveal about them?","How has going through this changed your family?","What do you want them to hold onto?","What are you most grateful for right now?"],
    defaultTempo:"Slow",
  },
  "parents|apology": {
    prompts:["What happened — in your own honest words?","What do you wish you'd done differently?","What do you want them to know about how you feel now?","What are you promising going forward?"],
    extendedPrompts:["What does your relationship with them mean to you?","What do you want them to understand about your feelings?","What does repair look like from here?","What have they given you that you want to acknowledge?"],
    defaultTempo:"Slow",
  },
  "parents|justbecause": {
    prompts:["What made you want to give them a song today — no occasion needed?","What do you love about them that you don't say enough?","What's a memory that captures who they are?","What do you want them to feel when they hear this?"],
    extendedPrompts:["What have they given you that you're only now starting to fully appreciate?","What's something small they do that shows enormous love?","What does your relationship with them look like right now?","What do you want them to always know?"],
    defaultTempo:"Slow",
  },
  "grandparent|justbecause": {
    prompts:["What made you want to do this for them today?","What do you love most about them that you rarely say?","What's a memory only the two of you share?","What do you want them to feel when they hear this?"],
    extendedPrompts:["What's a tradition or habit of theirs that is completely them?","What have they taught you without knowing it?","What do you hope they know about how loved they are?","What does your relationship with them mean to you?"],
    defaultTempo:"Slow",
  },
  "grandparent|retirement": {
    prompts:["What have they built or achieved over their career?","What's a specific memory or story from their working life?","What will the family miss about their work era?","What do you wish for them in this next chapter?"],
    extendedPrompts:["What's a funny shared memory from their working years?","What are they most known for professionally?","What wisdom have they shared about work and life?","What does retirement look like for them?"],
    defaultTempo:"Medium",
  },
  "child|birthday": {
    prompts:["What's something special about who they are right now, at this exact age?","What's your favourite moment with them this year?","What do you dream for their future?","How do you want them to feel when they hear this?"],
    extendedPrompts:["What makes them uniquely, irreplaceably themselves?","What do you hope they always remember about this time?","What do you want them to know about how much they're loved?","What has being their parent taught you?"],
    defaultTempo:"Medium",
  },
  "child|newbaby": {
    prompts:["What did you feel the moment you saw them?","What do you hope for their future?","What promises are you making to this new little person?","How has your life changed since they arrived?"],
    extendedPrompts:["What do you want them to know about the family they've joined?","What are you most excited to share with them as they grow?","Describe the first moment you held them.","What kind of person do you hope they become?"],
    defaultTempo:"Slow",
  },
  "child|graduation": {
    prompts:["What do you remember about the beginning of this journey?","What moment this year made you the proudest?","What do you want them to know as they step into what's next?","What are you wishing for them?"],
    extendedPrompts:["What have you watched them overcome?","What makes them extraordinary in your eyes?","What's a moment you'll carry forever from this chapter?","What do you want them to hold onto going forward?"],
    defaultTempo:"Upbeat",
  },
  "child|newchapter": {
    prompts:["What chapter are they stepping into?","What do you want to say as you watch them go?","What do you love about who they've become?","What are you wishing for them?"],
    extendedPrompts:["What has raising them taught you?","What will you miss most?","What do you hope they carry with them?","What do you want them to know they can always come back to?"],
    defaultTempo:"Medium",
  },
  "child|recovery": {
    prompts:["What did they fight through?","What moment made you realise how strong they truly are?","What do you want them to know about how you see them?","What does the road ahead look like now?"],
    extendedPrompts:["What did this experience teach you both?","What do you want them to hold onto when it gets hard again?","How has going through this together changed your relationship?"],
    defaultTempo:"Slow",
  },
  "child|memorial": {
    prompts:["What's the memory of them you'll always hold closest?","What do you miss most about their presence?","What did they teach you about love?","What do you want the world to know about who they were?"],
    extendedPrompts:["What would they say if they could hear this?","What small things carry them forward in your daily life?","What do you want them to know?","How do you keep them close?"],
    defaultTempo:"Slow",
  },
  "friend|birthday": {
    prompts:["How did you two become friends — the real story?","What's the most ridiculous memory you share?","What do you love about them that they probably don't know?","What are you wishing for them this year?"],
    extendedPrompts:["What have they taught you?","How have they shown up for you when it mattered?","What inside reference or shared joke would they love in this song?","How have they changed since you've known them?"],
    defaultTempo:"Upbeat",
  },
  "friend|wedding": {
    prompts:["How do you know the couple and how did you watch their love grow?","What's a memory of them together that you'll always hold onto?","What do you want to say about what their love means?","What are your wishes for them?"],
    extendedPrompts:["What makes them perfect for each other — specific, honest reasons?","What's something funny or tender from their relationship story?","What do you want the room to feel when this plays?","What do you hope for their future together?"],
    defaultTempo:"Medium",
  },
  "friend|justbecause": {
    prompts:["What made you want to do this for them today?","What do you love about your friendship that you never say out loud?","What's a moment that defines your bond?","What do you want them to feel?"],
    extendedPrompts:["What do they bring to your life that no one else does?","What's a shared memory that always makes you smile?","What would you want them to always know about how you see them?"],
    defaultTempo:"Medium",
  },
  "friend|longdistance": {
    prompts:["How did you end up living apart and how long has it been?","What do you miss most — be specific and honest?","What's a memory that always comes back to you?","What does your friendship look like across the distance?"],
    extendedPrompts:["What's something only the two of you would laugh about?","What do you want them to remember when they feel far away?","What does it feel like when you're finally together again?","What are you holding on to until next time?"],
    defaultTempo:"Medium",
  },
  "friend|newchapter": {
    prompts:["What chapter are they moving into?","What memory captures everything about your friendship?","What do you love about who they've become?","What do you want to say as you watch them go?"],
    extendedPrompts:["What are you most proud of about them?","What will your friendship look like from here?","What do you want them to carry with them?","What are you wishing for them?"],
    defaultTempo:"Upbeat",
  },
  "friend|roast": {
    prompts:["What is the most embarrassing thing they've done that everyone knows about?","What habit or quirk of theirs drives people completely mad?","What's the story that always gets told when they're not there?","What's the most 'them' thing they've ever done?"],
    extendedPrompts:["What do they think is cool that absolutely isn't?","What's something they've said that became a running joke?","What would their worst enemy and their best friend agree on?","What do you actually, genuinely love about them — sneak it in at the end?"],
    defaultTempo:"Upbeat",
  },
  "friend|memorial": {
    prompts:["What's the memory of them that lives most vividly in your mind?","What did they teach you about how to live?","What made them irreplaceable?","What do you want to say to them now?"],
    extendedPrompts:["What would they say if they could hear this?","What do you miss most about having them here?","What lives on in you because of them?","How do you carry them forward?"],
    defaultTempo:"Slow",
  },
  "grandparent|birthday": {
    prompts:["What do you love most about your grandparent?","What's a story or memory you'll always treasure?","What have they taught you about life — knowingly or not?","How do you want them to feel when they hear this?"],
    extendedPrompts:["What makes them special to the whole family?","What's a tradition, phrase, or habit that is completely them?","What do you hope they know about how much they're loved?","What do you want to celebrate about the life they've built?"],
    defaultTempo:"Slow",
  },
  "grandparent|thankyou": {
    prompts:["What's the most important thing they've given you or your family?","What's a memory that defines who they are?","What values did they pass down that live on in you?","What do you want them to hear?"],
    extendedPrompts:["What stories have they told that you'll always remember?","How have they shaped your family?","What do you want to celebrate about their life?","What do you hope they know they've built?"],
    defaultTempo:"Slow",
  },
  "grandparent|memorial": {
    prompts:["What's the memory of them you hold the most tightly?","What did they give to this family that lives on?","What would you want to say if you had one more moment?","How are they still present in everyday life?"],
    extendedPrompts:["What's something they always said that you still hear?","What do you miss most about them?","What do you want the younger generations to know about who they were?","How do they live on in the people they raised?"],
    defaultTempo:"Slow",
  },
  "sibling|birthday": {
    prompts:["What's the funniest memory you have with them — no filter?","What do you genuinely admire about them that you'd never say sober?","What does it mean to have them as your sibling?","What are you wishing for them?"],
    extendedPrompts:["What's a memory only a sibling would understand?","How have they shaped who you are?","What's something you've never properly said to them?","What do you love about who they've become?"],
    defaultTempo:"Upbeat",
  },
  "sibling|wedding": {
    prompts:["What's a memory of your sibling that captures exactly who they are?","What do you think of their partner — honestly and lovingly?","What do you want to say in front of everyone?","What are your wishes for their marriage?"],
    extendedPrompts:["What's the funniest thing that happened in the lead-up to today?","How have you watched them change since they found this person?","What do you hope their life together looks like?","What's something only a sibling would know to say?"],
    defaultTempo:"Medium",
  },
  "sibling|justbecause": {
    prompts:["What made you want to do this for them today?","What's a memory that is completely and utterly yours?","What do you love about them that you'd never say to their face?","What do you want them to feel?"],
    extendedPrompts:["What's the most 'them' thing they've ever done?","How have they shaped who you are without knowing it?","What would you want them to always know?"],
    defaultTempo:"Medium",
  },
  "sibling|recovery": {
    prompts:["What did they fight through?","What moment made you see how strong they really are?","What do you want them to know from a sibling's perspective?","What does the road ahead look like together?"],
    extendedPrompts:["How has this experience changed your relationship?","What do you want them to hold onto when it gets hard again?","What are you most proud of about them?"],
    defaultTempo:"Slow",
  },
  "sibling|newchapter": {
    prompts:["What chapter are they stepping into?","What's a memory that captures everything about your relationship?","What do you love about who they've become?","What do you want to say as you watch them go?"],
    extendedPrompts:["What are you most proud of about them?","What will your relationship look like from here?","What do you want them to carry with them?","What are you wishing for them — honestly?"],
    defaultTempo:"Medium",
  },
  "pet|justbecause": {
    prompts:["Describe your pet and their full, chaotic personality.","What's your favourite thing they do?","How has having them changed your life?","What would you say to them if they could understand?"],
    extendedPrompts:["What's the funniest thing they've ever done?","What do they always do when you come home?","What would they say about you if they could talk?","What's a habit of theirs that's annoying but you secretly love?"],
    defaultTempo:"Medium",
  },
  "pet|birthday": {
    prompts:["Describe your pet's personality like you're pitching a TV character.","What's the most chaotic thing they've done this year?","What does a perfect day look like from their perspective?","What would they say if they could give a birthday speech?"],
    extendedPrompts:["What do they love more than anything?","What is their sworn enemy (postman, vacuum, neighbour's cat)?","What do you love most about having them in your life?"],
    defaultTempo:"Upbeat",
  },
  "pet|memorial": {
    prompts:["What was their personality like — the real them?","What's the memory you'll hold most tightly?","What did having them teach you?","What do you want to say to them now?"],
    extendedPrompts:["What do you miss most about having them here?","What did they give you that nothing else can replace?","What will they always mean to you?","How do you keep them close?"],
    defaultTempo:"Slow",
  },
  "colleague|birthday": {
    prompts:["What is this person known for in the office — the real answer?","What's a memory or moment that captures who they are at work?","What do you genuinely appreciate about them?","What are you wishing for them today?"],
    extendedPrompts:["What's something funny that defines their work personality?","How have they made the team or workplace better?","What would the office be like without them?","What do you want them to know about how they're valued?"],
    defaultTempo:"Upbeat",
  },
  "colleague|leavingwork": {
    prompts:["What will people miss most about them — be specific and honest?","What's a legendary work story everyone knows?","What habit, phrase, or quirk of theirs is famous in the office?","What do you want to say on behalf of the team?"],
    extendedPrompts:["What's something they'd never admit they're proud of?","What's the most chaotic thing they were ever involved in at work?","What has the team genuinely learned from them?","What are you wishing for them in what comes next?"],
    defaultTempo:"Upbeat",
  },
  "colleague|retirement": {
    prompts:["What has this person built or achieved over their career?","What's a specific memory from working with them?","What will the team miss, honestly?","What do you wish them for this next chapter?"],
    extendedPrompts:["What's a funny shared memory from the years together?","What are they most known for?","What wisdom have they shared — knowingly or not?","What does life without them in the office actually look like?"],
    defaultTempo:"Medium",
  },
  "colleague|thankyou": {
    prompts:["What has this person done for you or the team that deserves a real thank you?","What specific impact have they had?","What's a memory of them going above and beyond?","What do you want them to know?"],
    extendedPrompts:["What have they taught you without realising it?","How has working with them changed how you work?","What do you hope they know about the difference they've made?"],
    defaultTempo:"Medium",
  },
  "colleague|roast": {
    prompts:["What is this person famous for in the office — good, bad, or legendary?","What habit of theirs has driven everyone quietly mad for years?","What's the story that always gets told at work events?","What do they think about themselves that everyone else finds hilarious?"],
    extendedPrompts:["What's something they've said that became an office in-joke?","What would their job title be if it were honest?","What's their relationship with the coffee machine / printer / meeting room?","What do you actually love about them — slip it in at the very end?"],
    defaultTempo:"Upbeat",
  },
  "self|birthday": {
    prompts:["What has this year actually looked like — the real version?","What are you most proud of about yourself right now?","What are you leaving behind going into the next year?","What do you want for yourself — no filter?"],
    extendedPrompts:["What have you learned about yourself this year?","What would last year's version of you think of you now?","What's one thing you've finally let go of?","What does the next chapter look like?"],
    defaultTempo:"Upbeat",
  },
  "self|newchapter": {
    prompts:["What chapter are you stepping into?","What are you leaving behind?","What does this new version of your life look like?","What do you want this song to make you feel every time you hear it?"],
    extendedPrompts:["What has brought you to this point?","What are you most excited about?","What are you most afraid of — and leaning into anyway?","What do you want to remind yourself of when it gets hard?"],
    defaultTempo:"Upbeat",
  },
  "self|recovery": {
    prompts:["What did you fight through?","What does the version of you who made it through look like?","What do you know now that you didn't before?","What do you want this song to say to you when you need it most?"],
    extendedPrompts:["What was the hardest moment?","What kept you going?","Who or what do you want to acknowledge?","What does the road ahead look like from here?"],
    defaultTempo:"Medium",
  },
  "self|divorce": {
    prompts:["What chapter is closing and what's opening?","What are you reclaiming about yourself?","What do you want to feel when this song plays?","What does freedom look like right now?"],
    extendedPrompts:["What did you learn about yourself through this?","What are you leaving behind — genuinely and completely?","What are you excited about that you haven't admitted yet?","What do you want to tell yourself six months from now?"],
    defaultTempo:"Upbeat",
  },
  "self|graduation": {
    prompts:["What has this journey actually cost you — honestly?","What are you most proud of?","What do you know now that you didn't when you started?","What's next, and what does it feel like?"],
    extendedPrompts:["What would you say to the version of you who started?","Who do you want to acknowledge?","What do you want to remember about this moment?","What are you stepping into?"],
    defaultTempo:"Upbeat",
  },
  "ex|justbecause": {
    prompts:["What do you want to say that you never properly got to?","What was real about what you had — what do you want to honour?","Where are you now with all of it?","What does moving forward look like for you?"],
    extendedPrompts:["What did you love about them that you'll always carry?","What did the relationship teach you about yourself?","What do you want them to know without it being complicated?","What does closure mean to you?"],
    defaultTempo:"Slow",
  },
  "*|memorial": {
    prompts:["What's the memory of them you hold closest?","What did they give to the people around them?","What would you say if you had one more moment?","How do you want this song to feel?"],
    extendedPrompts:["What's something they always said that you still hear?","What do you miss most?","How do they live on in the people who loved them?","What do you want the world to know about who they were?"],
    defaultTempo:"Slow",
  },
  "*|recovery": {
    prompts:["What did they face and what did it take to get through?","What moment showed you how strong they are?","What do you want them to know from where you're standing?","What does the road ahead look like?"],
    extendedPrompts:["What did this experience reveal about them?","How has it changed your relationship?","What do you want them to hold onto?","What are you proud of — specific and honest?"],
    defaultTempo:"Slow",
  },
  "*|roast": {
    prompts:["What are they most infamous for — the story everyone knows?","What habit or quirk of theirs is legendary?","What do they think about themselves that others find hilarious?","What's the funniest thing they've ever done — genuinely?"],
    extendedPrompts:["What would their honest job title / life title be?","What's something they've said that became a running joke?","What do they love that no one else understands?","What do you actually love about them — the genuine bit at the end?"],
    defaultTempo:"Upbeat",
  },
  "*|apology": {
    prompts:["What happened — in your own honest, undefended words?","What do you wish you'd done differently?","What do you want them to know about how you feel now?","What are you promising going forward?"],
    extendedPrompts:["What does this relationship mean to you?","What do you want them to understand that you struggle to say?","What does repair look like from here?"],
    defaultTempo:"Slow",
  },
  "*|newchapter": {
    prompts:["What chapter are they stepping into?","What do you want to say as you watch them go?","What do you love about who they've become?","What are you wishing for them?"],
    extendedPrompts:["What's a memory that captures everything about your relationship?","What do you hope they carry with them?","What will you miss?","What are you most proud of about them?"],
    defaultTempo:"Medium",
  },
  "default": {
    prompts:["Who is this person and what makes them genuinely special?","What is your most cherished memory with them?","What do you want them to feel when they hear this song?","What are your wishes for their future?"],
    extendedPrompts:["Is there a place that's important in your story together?","What's a phrase, word, or saying that represents them?","How has knowing them changed you?","What would you say if you knew they were listening right now?","Describe them in exactly 3 words.","What do others not see about them that you do?"],
    defaultTempo:"Medium",
  },
},

};
